name: room_allocation_system
description: "Engineering Building Room Allocation System"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  onesignal_flutter: ^5.2.0
  http: ^1.1.0

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^13.0.0

  # Date/time
  intl: ^0.19.0

  # Calendar
  table_calendar: ^3.1.0

  # Image loading
  cached_network_image: ^3.3.1

  # Lost & Found
  image_picker: ^1.1.2
  uuid: ^4.5.1
  google_fonts: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/RAS_launcher_logo.png"
  adaptive_icon_background: "#ffffff" # Suggested white background for better visibility
  adaptive_icon_foreground: "assets/images/RAS_launcher_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/RAS_logo.png
    - assets/images/RAS_launcher_logo.png
