// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJIHAmk9mndhfZ1DgM6_YiQb8VZFoqm8M',
    appId: '1:1077283760082:web:f32cf58a4773d243b60a0b',
    messagingSenderId: '1077283760082',
    projectId: 'room-availability-app-8371b',
    authDomain: 'room-availability-app-8371b.firebaseapp.com',
    storageBucket: 'room-availability-app-8371b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbEctB3QeA57j5zXolLb5x_5l1gjVuXQ',
    appId: '1:1077283760082:android:6958b363d1d5c7ffb60a0b',
    messagingSenderId: '1077283760082',
    projectId: 'room-availability-app-8371b',
    storageBucket: 'room-availability-app-8371b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD89BZZk-f2FUEKFbCbxekP1gmLz4cXNJE',
    appId: '1:1077283760082:ios:1b96cc218dc2fd4eb60a0b',
    messagingSenderId: '1077283760082',
    projectId: 'room-availability-app-8371b',
    storageBucket: 'room-availability-app-8371b.firebasestorage.app',
    iosClientId: '1077283760082-jkes2vq0i10li5b6n2ltvvl519jq09sn.apps.googleusercontent.com',
    iosBundleId: 'com.yourname.roomAvailabilityApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD89BZZk-f2FUEKFbCbxekP1gmLz4cXNJE',
    appId: '1:1077283760082:ios:1b96cc218dc2fd4eb60a0b',
    messagingSenderId: '1077283760082',
    projectId: 'room-availability-app-8371b',
    storageBucket: 'room-availability-app-8371b.firebasestorage.app',
    iosClientId: '1077283760082-jkes2vq0i10li5b6n2ltvvl519jq09sn.apps.googleusercontent.com',
    iosBundleId: 'com.yourname.roomAvailabilityApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJIHAmk9mndhfZ1DgM6_YiQb8VZFoqm8M',
    appId: '1:1077283760082:web:08d357740b54a8dab60a0b',
    messagingSenderId: '1077283760082',
    projectId: 'room-availability-app-8371b',
    authDomain: 'room-availability-app-8371b.firebaseapp.com',
    storageBucket: 'room-availability-app-8371b.firebasestorage.app',
  );
}
